title: eHealth Lab                        # Title in top navigation bar (navbar) and <head>
description: The eHealth Lab website

theme: jekyll-theme-modernist
remote-theme:  peterdesmet/petridish@1.1

paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-scholar
 
